title: OrgCheck
email: vfinet@salesforce.com
description: OrgCheck is an easy-to-install and easy-to-use Salesforce application in order to quickly analyze your org and its technical debt.
twitter_username: VinceFINET
github_username:  VinceFINET
theme: jekyll-theme-minimal
logo: assets/pngs/Logo+Mascot-2.png

pages:
  - home: Home
  - preview: Preview
  - installation: Install
  - vision: Vision
  - legal: Legal Terms
  - technical:
    - datastores: Data Stores in OrgCheck
    - ds_flows: Flows
    - ds_packages: Packages
    - ds_workflowrules: Workflow Rules
