title: OrgCheck
email: vfinet@salesforce.com
description: OrgCheck is an easy-to-install and easy-to-use Salesforce application in order to quickly analyze your org and its technical debt.
twitter_username: VinceFINET
github_username:  VinceFINET
theme: jekyll-theme-minimal
logo: assets/pngs/Logo+Mascot-2.png

page_home: 
  - label: Home
  - url: /home
page_preview:  
  - label: Preview
  - url: /preview
page_installation:  
  - label: Install
  - url: /installation
page_vision:  
  - label: Vision
  - url: /vision
page_legal:  
  - label: Legal Terms
  - url: /legal
page_tech_datastores:  
  - label: Data Stores in OrgCheck
  - url: /technical/datastores
page_tech_ds_flows:  
  - label: Flows
  - url: /technical/datastores/flows
page_tech_ds_packages:  
  - label: Packages
  - url: /technical/datastores/packages
page_tech_ds_workflowrules:  
  - label: Workflow Rules
  - url: /technical/datastores/workflowrules
