title: OrgCheck
email: vfinet@salesforce.com
description: OrgCheck is an easy-to-install and easy-to-use Salesforce application in order to quickly analyze your org and its technical debt.
twitter_username: VinceFINET
github_username:  VinceFINET
theme: jekyll-theme-minimal
logo: assets/pngs/Logo+Mascot-2.png

page_home: / 
page_preview: preview
page_install: installation
page_vision: vision
page_legal: legal
